#!/bin/bash
# Chrome Automation Stealth Fix for Clawdbot + Jupiter
# Created: 2025-01-27

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CHROME_APP="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
PROFILE_DIR="$HOME/.chrome-jupiter-stealth"
CLAWDBOT_CHROME_JS="/opt/homebrew/lib/node_modules/clawdbot/dist/browser/chrome.js"

echo "🦞 Clawdbot Chrome Stealth Fix Installer"
echo "========================================"
echo ""

# Check if Chrome exists
if [ ! -f "$CHROME_APP" ]; then
    echo "❌ Chrome not found at: $CHROME_APP"
    echo "Please update CHROME_APP variable in this script"
    exit 1
fi

echo "✅ Found Chrome: $CHROME_APP"
echo ""

# Menu
echo "Choose fix method:"
echo ""
echo "1) Extension Profile (RECOMMENDED - No system modifications)"
echo "   - Creates custom Chrome launch script with stealth flags"
echo "   - Use Clawdbot extension to control manually-launched Chrome"
echo ""
echo "2) Patch Clawdbot Code (ADVANCED - Modifies system files)"
echo "   - Adds stealth flags to Clawdbot's Chrome launcher"
echo "   - Requires sudo access"
echo ""
echo "3) Both (Extension + Code Patch)"
echo ""
read -p "Enter choice (1-3): " choice

case $choice in
    1|3)
        echo ""
        echo "=== Setting up Extension Profile ==="
        echo ""
        
        # Create launch script
        LAUNCH_SCRIPT="$HOME/launch-chrome-jupiter.sh"
        
        cat > "$LAUNCH_SCRIPT" << 'EOFLAUNCH'
#!/bin/bash
# Chrome launcher with stealth flags for Jupiter/Clawdbot
# Auto-generated by fix-chrome-stealth.sh

CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
PROFILE="$HOME/.chrome-jupiter-stealth"

echo "🚀 Launching Chrome with stealth flags..."
echo "Profile: $PROFILE"
echo ""
echo "After Chrome opens:"
echo "1. Load Jupiter extension"
echo "2. Load Clawdbot extension from: $(clawdbot browser extension path)"
echo "3. Click Clawdbot extension icon to attach"
echo ""

"$CHROME" \
    --remote-debugging-port=9222 \
    --disable-blink-features=AutomationControlled \
    --disable-automation \
    --disable-dev-shm-usage \
    --user-data-dir="$PROFILE" \
    --no-first-run \
    --no-default-browser-check \
    about:blank &

CHROME_PID=$!
echo "✅ Chrome launched (PID: $CHROME_PID)"
echo ""
echo "Test with: clawdbot browser --browser-profile chrome status"
EOFLAUNCH
        
        chmod +x "$LAUNCH_SCRIPT"
        
        echo "✅ Created launch script: $LAUNCH_SCRIPT"
        echo ""
        echo "Next steps:"
        echo "1. Run: $LAUNCH_SCRIPT"
        echo "2. Install Clawdbot extension:"
        echo "   - Run: clawdbot browser extension install"
        echo "   - Go to chrome://extensions"
        echo "   - Enable 'Developer mode'"
        echo "   - Click 'Load unpacked'"
        echo "   - Select: $(clawdbot browser extension path 2>/dev/null || echo '<run command to get path>')"
        echo "3. Load Jupiter extension manually"
        echo "4. Click Clawdbot extension icon to attach"
        echo "5. Test: clawdbot browser --browser-profile chrome tabs"
        echo ""
        
        if [ "$choice" != "3" ]; then
            echo "✅ Extension profile setup complete!"
            exit 0
        fi
        ;;
esac

case $choice in
    2|3)
        echo ""
        echo "=== Patching Clawdbot Code ==="
        echo ""
        echo "⚠️  WARNING: This modifies system files"
        echo "⚠️  Changes will be lost on Clawdbot updates"
        echo ""
        read -p "Continue? (y/N): " confirm
        
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            echo "Aborted."
            exit 0
        fi
        
        # Check if file exists
        if [ ! -f "$CLAWDBOT_CHROME_JS" ]; then
            echo "❌ Clawdbot chrome.js not found at: $CLAWDBOT_CHROME_JS"
            exit 1
        fi
        
        # Check if already patched
        if grep -q "disable-blink-features=AutomationControlled" "$CLAWDBOT_CHROME_JS"; then
            echo "✅ Already patched!"
        else
            echo "Creating backup..."
            sudo cp "$CLAWDBOT_CHROME_JS" "$CLAWDBOT_CHROME_JS.backup-$(date +%Y%m%d-%H%M%S)"
            
            echo "Applying patch..."
            
            # Create patch script
            PATCH_SCRIPT=$(mktemp)
            cat > "$PATCH_SCRIPT" << 'EOFPATCH'
const fs = require('fs');
const file = process.argv[2];
let content = fs.readFileSync(file, 'utf8');

// Find the args array definition and add stealth flags
const searchPattern = '"--password-store=basic",';
const replacement = `"--password-store=basic",
            "--disable-blink-features=AutomationControlled",
            "--disable-automation",`;

if (content.includes('--disable-blink-features=AutomationControlled')) {
    console.log('Already patched!');
    process.exit(0);
}

if (!content.includes(searchPattern)) {
    console.error('Could not find insertion point in chrome.js');
    console.error('Manual patching required.');
    process.exit(1);
}

content = content.replace(searchPattern, replacement);
fs.writeFileSync(file, content, 'utf8');
console.log('✅ Patch applied successfully!');
EOFPATCH
            
            sudo node "$PATCH_SCRIPT" "$CLAWDBOT_CHROME_JS"
            rm "$PATCH_SCRIPT"
            
            echo ""
            echo "Restarting Clawdbot gateway..."
            clawdbot gateway restart
            sleep 2
            
            echo ""
            echo "✅ Code patch complete!"
        fi
        
        echo ""
        echo "Next steps:"
        echo "1. Test: clawdbot browser --browser-profile clawd status"
        echo "2. Visit: https://bot.sannysoft.com/ to verify stealth"
        echo ""
        echo "⚠️  Remember: Patch will be lost on 'npm update clawdbot'"
        echo "   Re-run this script after updates"
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "=== Testing Resources ==="
echo "Test automation detection:"
echo "  • https://bot.sannysoft.com/"
echo "  • https://arh.antoinevastel.com/bots/areyouheadless"
echo "  • https://pixelscan.net/"
echo ""
echo "Commands:"
echo "  • clawdbot browser status"
echo "  • clawdbot browser tabs"
echo "  • clawdbot browser open <url>"
echo ""
echo "✅ Setup complete!"
