#!/bin/bash
# SLEEP CONSOLIDATION SYSTEM
# Runs nightly to consolidate memories, archive old logs, update state
# Mimics hippocampal sleep replay + consolidation

set -e

# Detect workspace (parent of scripts folder)
WORKSPACE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MEMORY_DIR="$WORKSPACE_DIR/memory"
ARCHIVE_DIR="$MEMORY_DIR/archive"
TODAY=$(date +%Y-%m-%d)

# Cross-platform date calculation
if [[ "$OSTYPE" == "darwin"* ]]; then
    WEEK_AGO=$(date -v-7d +%Y-%m-%d)
else
    WEEK_AGO=$(date -d "7 days ago" +%Y-%m-%d)
fi

echo "🌙 SLEEP CYCLE STARTING - $(date)"
echo "================================================"
echo "Workspace: $WORKSPACE_DIR"

# Create archive directory if needed
mkdir -p "$ARCHIVE_DIR"

# 1. ARCHIVE OLD DAILY LOGS (older than 7 days)
echo ""
echo "📦 Phase 1: Archiving old daily logs..."
archived_count=0
for file in "$MEMORY_DIR"/20*.md; do
    if [[ -f "$file" ]]; then
        filename=$(basename "$file")
        filedate="${filename%.md}"
        if [[ "$filedate" < "$WEEK_AGO" ]]; then
            mv "$file" "$ARCHIVE_DIR/"
            echo "   Archived: $filename"
            ((archived_count++)) || true
        fi
    fi
done
echo "   Total archived: $archived_count files"

# 2. LIST HIGH-PRIORITY ITEMS FOR REVIEW
echo ""
echo "🔴 Phase 2: Identifying high-priority items..."
grep -r "importance: high\|IMPORTANT\|CRITICAL\|remember this" "$MEMORY_DIR" 2>/dev/null | head -20 || echo "   No explicit high-priority markers found"

# 3. CHECK FOR STALE CURRENT_STATE
echo ""
echo "📋 Phase 3: Checking CURRENT_STATE.md freshness..."
if [[ -f "$WORKSPACE_DIR/CURRENT_STATE.md" ]]; then
    state_date=$(grep "Last Updated:" "$WORKSPACE_DIR/CURRENT_STATE.md" | head -1 || echo "unknown")
    echo "   $state_date"
else
    echo "   ⚠️  CURRENT_STATE.md not found!"
fi

# 4. MEMORY STATISTICS
echo ""
echo "📊 Phase 4: Memory statistics..."
total_files=$(find "$MEMORY_DIR" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
total_size=$(du -sh "$MEMORY_DIR" 2>/dev/null | cut -f1)
archive_files=$(find "$ARCHIVE_DIR" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
echo "   Active memory files: $total_files"
echo "   Archived files: $archive_files"
echo "   Total memory size: $total_size"

# 5. GENERATE CONSOLIDATION REPORT
echo ""
echo "📝 Phase 5: Generating consolidation report..."
report_dir="$MEMORY_DIR/sleep-reports"
mkdir -p "$report_dir"
report_file="$report_dir/$(date +%Y-%m-%d)-sleep.md"

cat > "$report_file" << EOF
# Sleep Consolidation Report
**Date:** $(date +"%Y-%m-%d %H:%M %Z")

## Summary
- Files archived: $archived_count
- Active memory files: $total_files
- Archived files: $archive_files
- Total memory size: $total_size

## Actions Taken
- Archived daily logs older than 7 days
- Scanned for high-priority items
- Verified CURRENT_STATE.md exists

---
*Generated by Sleep Consolidation System*
EOF

echo "   Report saved: $report_file"

# 6. DONE
echo ""
echo "================================================"
echo "✅ SLEEP CYCLE COMPLETE - $(date)"
echo "🌅 Ready for next session"
