#!/bin/bash
# ATLAS SLEEP CONSOLIDATION SYSTEM
# Runs nightly to consolidate memories, archive old logs, update state
# Mimics hippocampal sleep replay + consolidation

set -e

CLAWD_DIR="$HOME/clawd"
MEMORY_DIR="$CLAWD_DIR/memory"
ARCHIVE_DIR="$MEMORY_DIR/archive"
TODAY=$(date +%Y-%m-%d)
WEEK_AGO=$(date -v-7d +%Y-%m-%d 2>/dev/null || date -d "7 days ago" +%Y-%m-%d)

echo "🌙 ATLAS SLEEP CYCLE STARTING - $(date)"
echo "================================================"

# Create archive directory if needed
mkdir -p "$ARCHIVE_DIR"

# 1. ARCHIVE OLD DAILY LOGS (older than 7 days)
echo ""
echo "📦 Phase 1: Archiving old daily logs..."
archived_count=0
for file in "$MEMORY_DIR"/20*.md; do
    if [[ -f "$file" ]]; then
        filename=$(basename "$file")
        filedate="${filename%.md}"
        # Check if file is older than 7 days
        if [[ "$filedate" < "$WEEK_AGO" ]]; then
            mv "$file" "$ARCHIVE_DIR/"
            echo "   Archived: $filename"
            ((archived_count++)) || true
        fi
    fi
done
echo "   Total archived: $archived_count files"

# 2. LIST HIGH-PRIORITY ITEMS FOR REVIEW
echo ""
echo "🔴 Phase 2: Identifying high-priority items..."
echo "   Scanning for importance markers..."

# Look for items tagged as important
grep -r "importance: high\|IMPORTANT\|CRITICAL\|remember this" "$MEMORY_DIR" 2>/dev/null | head -20 || echo "   No explicit high-priority markers found"

# 3. CHECK FOR STALE CURRENT_STATE
echo ""
echo "📋 Phase 3: Checking CURRENT_STATE.md freshness..."
if [[ -f "$CLAWD_DIR/CURRENT_STATE.md" ]]; then
    state_date=$(grep "Last Updated:" "$CLAWD_DIR/CURRENT_STATE.md" | head -1 || echo "unknown")
    echo "   $state_date"
else
    echo "   ⚠️  CURRENT_STATE.md not found!"
fi

# 4. MEMORY STATISTICS
echo ""
echo "📊 Phase 4: Memory statistics..."
total_files=$(find "$MEMORY_DIR" -name "*.md" -type f | wc -l | tr -d ' ')
total_size=$(du -sh "$MEMORY_DIR" 2>/dev/null | cut -f1)
archive_files=$(find "$ARCHIVE_DIR" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
echo "   Active memory files: $total_files"
echo "   Archived files: $archive_files"
echo "   Total memory size: $total_size"

# 5. TRADING POSITIONS CHECK
echo ""
echo "💰 Phase 5: Checking active trading positions..."
if [[ -f "$MEMORY_DIR/trading/active-positions.md" ]]; then
    positions=$(grep -c "^\|" "$MEMORY_DIR/trading/active-positions.md" 2>/dev/null || echo "0")
    echo "   Active positions file exists"
    # Show last modified time
    ls -la "$MEMORY_DIR/trading/active-positions.md" | awk '{print "   Last modified: " $6, $7, $8}'
else
    echo "   ⚠️  No active-positions.md found"
fi

# 6. GENERATE CONSOLIDATION REPORT
echo ""
echo "📝 Phase 6: Generating consolidation report..."
report_file="$MEMORY_DIR/sleep-reports/$(date +%Y-%m-%d)-sleep.md"
mkdir -p "$MEMORY_DIR/sleep-reports"

cat > "$report_file" << EOF
# Sleep Consolidation Report
**Date:** $(date +"%Y-%m-%d %H:%M %Z")

## Summary
- Files archived: $archived_count
- Active memory files: $total_files
- Archived files: $archive_files
- Total memory size: $total_size

## Actions Taken
- Archived daily logs older than 7 days
- Scanned for high-priority items
- Verified CURRENT_STATE.md exists

## Recommendations
$(if [[ $archived_count -gt 5 ]]; then echo "- Consider reviewing archived files for important patterns"; fi)
$(if [[ $total_files -gt 50 ]]; then echo "- Memory file count high - consider consolidating"; fi)

---
*Generated by Atlas Sleep Consolidation System*
EOF

echo "   Report saved: $report_file"

# 7. DONE
echo ""
echo "================================================"
echo "✅ ATLAS SLEEP CYCLE COMPLETE - $(date)"
echo "🌅 Ready for next session"
