#!/usr/bin/env python3
"""
ATLAS WEEKLY CONSOLIDATION
Mimics slower neocortical consolidation - summarizes daily logs into weekly summaries.
Runs once per week, creates high-level patterns from daily noise.
"""

import os
from datetime import datetime, timedelta
from pathlib import Path
import re

CLAWD_DIR = Path.home() / "clawd"
MEMORY_DIR = CLAWD_DIR / "memory"
WEEKLY_DIR = MEMORY_DIR / "weekly"

def get_week_range():
    """Get the date range for last week."""
    today = datetime.now()
    # Get last Sunday
    days_since_sunday = (today.weekday() + 1) % 7
    last_sunday = today - timedelta(days=days_since_sunday)
    last_monday = last_sunday - timedelta(days=6)
    return last_monday, last_sunday

def find_daily_logs(start_date, end_date):
    """Find all daily log files in date range."""
    logs = []
    current = start_date
    while current <= end_date:
        date_str = current.strftime("%Y-%m-%d")
        log_path = MEMORY_DIR / f"{date_str}.md"
        if log_path.exists():
            logs.append((date_str, log_path.read_text()))
        current += timedelta(days=1)
    return logs

def extract_key_items(content):
    """Extract key items from a daily log."""
    items = {
        "decisions": [],
        "wins": [],
        "problems": [],
        "insights": [],
        "todos": []
    }
    
    lines = content.split('\n')
    current_section = None
    
    for line in lines:
        line_lower = line.lower()
        
        # Detect sections
        if 'decision' in line_lower or 'decided' in line_lower:
            current_section = "decisions"
        elif 'win' in line_lower or 'success' in line_lower or '✅' in line:
            current_section = "wins"
        elif 'problem' in line_lower or 'issue' in line_lower or 'bug' in line_lower or '❌' in line:
            current_section = "problems"
        elif 'insight' in line_lower or 'learned' in line_lower or 'realize' in line_lower:
            current_section = "insights"
        elif 'todo' in line_lower or 'task' in line_lower or '[ ]' in line:
            current_section = "todos"
        
        # Extract bullet points
        if line.strip().startswith(('-', '*', '•')) and len(line.strip()) > 5:
            if current_section and current_section in items:
                items[current_section].append(line.strip())
    
    return items

def generate_weekly_summary(logs):
    """Generate a weekly summary from daily logs."""
    week_start, week_end = get_week_range()
    
    all_items = {
        "decisions": [],
        "wins": [],
        "problems": [],
        "insights": [],
        "todos": []
    }
    
    for date_str, content in logs:
        items = extract_key_items(content)
        for key in all_items:
            all_items[key].extend(items[key])
    
    # Build summary
    summary = []
    summary.append(f"# Weekly Summary: {week_start.strftime('%Y-%m-%d')} to {week_end.strftime('%Y-%m-%d')}")
    summary.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    summary.append(f"**Daily logs processed:** {len(logs)}")
    summary.append("")
    
    summary.append("## 🏆 Wins")
    if all_items["wins"]:
        for item in all_items["wins"][:10]:
            summary.append(item)
    else:
        summary.append("- (No explicit wins logged)")
    summary.append("")
    
    summary.append("## 🎯 Key Decisions")
    if all_items["decisions"]:
        for item in all_items["decisions"][:10]:
            summary.append(item)
    else:
        summary.append("- (No explicit decisions logged)")
    summary.append("")
    
    summary.append("## 💡 Insights")
    if all_items["insights"]:
        for item in all_items["insights"][:10]:
            summary.append(item)
    else:
        summary.append("- (No explicit insights logged)")
    summary.append("")
    
    summary.append("## ⚠️ Problems Encountered")
    if all_items["problems"]:
        for item in all_items["problems"][:10]:
            summary.append(item)
    else:
        summary.append("- (No major problems logged)")
    summary.append("")
    
    summary.append("## 📋 Carried-Over TODOs")
    if all_items["todos"]:
        for item in all_items["todos"][:10]:
            summary.append(item)
    else:
        summary.append("- (No pending TODOs)")
    summary.append("")
    
    summary.append("---")
    summary.append("*Generated by Atlas Weekly Consolidation (neocortical slow-learning analog)*")
    
    return "\n".join(summary)

def main():
    print("📅 ATLAS WEEKLY CONSOLIDATION")
    print("=" * 50)
    
    # Create weekly directory
    WEEKLY_DIR.mkdir(exist_ok=True)
    
    # Get date range
    week_start, week_end = get_week_range()
    print(f"Processing: {week_start.strftime('%Y-%m-%d')} to {week_end.strftime('%Y-%m-%d')}")
    
    # Find logs
    logs = find_daily_logs(week_start, week_end)
    print(f"Found {len(logs)} daily logs")
    
    if not logs:
        print("No daily logs found for this week. Nothing to consolidate.")
        return
    
    # Generate summary
    summary = generate_weekly_summary(logs)
    
    # Save
    week_str = week_start.strftime("%Y-W%W")
    output_path = WEEKLY_DIR / f"{week_str}-summary.md"
    output_path.write_text(summary)
    
    print(f"\n{summary}")
    print(f"\n📝 Saved to: {output_path}")

if __name__ == "__main__":
    main()
